spring.application.name=InterviewTracking

spring.datasource.url=jdbc:postgresql://localhost:5432/interview_tracking
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=change-this-jwt-secret-key-minimum-32-chars
